### ISSUE TITLE
Setuptools Bootstrapper script is deprecated

### ISSUE THREAD

**Issue by GedLawrenson** [QISKit/qiskit-sdk-py#1]
Hi 👋 

Per the header of the Setuptools bootstrapper script (https://bootstrap.pypa.io/ez_setup.py), this installation method is deprecated.

Equally the "curl | python" pattern might not be a great idea - https://jordaneldredge.com/blog/one-way-curl-pipe-sh-install-scripts-can-be-dangerous/

I'll try to look for an alternative when I am I front of a laptop 👍.

**Comment by diego-plan9** [comment]
Closing this issue as hopefully it has been addressed a while ago, specially since #35 and the introduction of a standard `pip install qiskit` method (plus the alternate installation methods on the README and documentation). Thanks for reporting, and please don't hesitate on reopening if you feel further discussion or actions are required!
