### ISSUE TITLE
Cannot build qiskit: package directory 'qiskit/simulators' does not exist

### ISSUE THREAD

**Issue by r3versi** [QISKit/qiskit-sdk-py#120]
Hello, 

I'm pretty new to qiskit and I may have misunderstood the issue, but I cannot build the package due to a missing package folder: simulators

```
$ python setup.py build
running build
running build_py
error: package directory 'qiskit/simulators' does not exist
```

I suppose that's due to the new backends interface implementation, so maybe setup.py should be updated to reflect the change, here: https://github.com/QISKit/qiskit-sdk-py/blob/master/setup.py#L12

* Version used: 0.4.0
* Environment name and version: Python 3.6.2
* Operating System and version: Linux 4.10.0-37-generic

**Comment by diego-plan9** [comment]
Hello @r3versi,

thanks for reporting! A fix for the invalid package name declaration is included among the changes on PR #115, which is still not merged - and some other tweaks might be needed to ensure being able to `build` the package properly due to recent changes.

It should be fixed shortly, but in the meantime (and if applicable in your scenario) perhaps using the [alternative installation methods](https://github.com/QISKit/qiskit-sdk-py#installation) would be an option?

**Comment by r3versi** [comment]
Hi @diego-plan9, thanks for the fast answer. I actually installed the package simply replacing qiskit.simulators by qiskit.backends at line 12 of setup.py and everything built smoothly :+1:

**Comment by diego-plan9** [comment]
I'm glad you were able to get it working, @r3versi ! I'm closing the issue as the issue should be address on the mentioned PR, but don't hesitate of reopening or issuing a new one if needed.
