### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by awcross1** [QISKit/qiskit-sdk-py#240]
Add an FAQ to address common questions about QISKit and quantum computing, and provide link to it from the landing page qiskit.org.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by diego-plan9** [comment]
We actually have a (slim) troubleshooting wiki page at https://github.com/QISKit/qiskit-sdk-py/wiki/QISKit-Troubleshooting, but I think it would be indeed be a good idea to have a more general FAQ: I'm unsure about the best place (ie. on a `.md` file, as part of the sphinx documentation, on the wiki ...) - any suggestions or preferences?

There might also be some overlap with the existing information at https://github.com/QISKit/ibmqx-user-guides (specially for the "generic quantum computing FAQs") that ideally we should factor in as well.

**Comment by jaygambetta** [comment]
I think md file is best so that it can be read and added to qiskit.org.  I think the faq here should focus on for quantum programming and using qiskit vs quantum information science and understanding what we could do which is the one in the user guide.  But you are correct they need to be linked and guidelines clearly stated.
