### ISSUE TITLE
No matching distribution found for qiskit

### ISSUE THREAD

**Issue by PabloAMC** [QISKit/qiskit-sdk-py#266]
When I run
sudo -H pip install qiskit
I get back
Could not find a version that satisfies the requirement qiskit (from versions: )
No matching distribution found for qiskit

* Environment name and version: Python 3.5.2
* Operating System and version: Ubuntu 14.04

**Comment by diego-plan9** [comment]
Hello @PabloAMC,

can you double-check that Python 3 is the default interpreter (and the one used by the system-wide `pip` command) in your system? You can find it out by executing something similar to:
```
sudo -H pip --version
```

as the message suggests you are using Python 2 (and QISKit requires Python 3) - if that is the case, please refer to your distribution documentation in order to install a Python 3 interpreter (or if you have both available, use the `pip` from Python3 instead - a common solution is use a Python 3 virtualenv via `virtualenv --python=python3 myqiskitfolder`).

**Comment by diego-plan9** [comment]
I'm closing the issue, in the hopes it has been solved by the comment above - please feel free to reopen if it's not the case.
