### ISSUE TITLE
Circuit `initialize` uses non-basis gates

### ISSUE THREAD

**Issue by hushaohan** [QISKit/qiskit-sdk-py#448]
The current circuit `initialize` uses non-basis gates, preventing the use of `skip_translation`.

**Comment by ajavadia** [comment]
I don't think this is a bug. `skip_translation` by definition is not guaranteed to work with every input and every basis gate. When you use it, you basically take responsibility for ensuring your circuit has the correct gates for the backend you select. In this case, it is not hard to do since `initialize` creates `cx`, `rz` and `ry` gates. If you want to change that to the `u1,u2,u3,cx` basis, you basically have to replace `rz(phi)` -> `u1(phi)` and `ry(theta)` -> `u3(theta,0,0)`

**Comment by hushaohan** [comment]
How do you do the replacements on the circuit produced by `initialize`?

**Comment by hushaohan** [comment]
Does QISKit provide a method to facilitate said replacement?

**Comment by ajavadia** [comment]
@hushaohan right now the compiler does those translations, something you want to avoid with the skip_translation flag. Once the transpiler (#422) is in place, you will be able to ask for just that part of the translation. For now, i think it is straightforward to just do a string replacement following the above rules. You should do this on the output of the `compile`, which is a dictionary.
