### ISSUE TITLE
One shot circuit with measurement

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-sdk-py#513]
I want to demonstrate a quantum algorithm with deterministic success probability (one). This can be done with 1-shot computation on the simulator. But the current simulator will issue a warning as below:
```
/Users/.../miniconda3/envs/QISKitenv/lib/python3.6/site-packages/qiskit/backends/local/qasm_simulator_cpp.py:99: DeprecationWarning: The behavior of getting statevector from simulators by setting shots=1 is deprecated and will be removed. Use the local_statevector_simulator instead, or place explicit snapshot instructions.
  DeprecationWarning)
``` 

It asks me to use `local_statevector_simulator`, but the `local_statevector_simulator` does not accept circuit with measurement, which is a contradiction. 

## Expected Behavior

Allow users to run simulator with `shot=1` without warning. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.5.2
* Environment name and version (e.g. Python 3.6.1): 3.6.x
* Operating System and version: MacOSX

**Comment by ajavadia** [comment]
This warning is emitted because in previous versions we had a somewhat hidden functionality that if you set `shots=1` in the `local_qasm_simulator`, you would get the statevector in the result. Since this functionality is deprecated in favor of `local_statevector_simulator`, we need to have a DeprecationWarning for users coming from the old code. This will be removed after a little while (in version 0.6).
