### ISSUE TITLE
Possible implementation for cont_gates according to Barenco 

### ISSUE THREAD

**Issue by sensor1** [QISKit/qiskit-sdk-py#59]
[controlledU.tar.gz](https://github.com/QISKit/qiskit-sdk-py/files/1277530/controlledU.tar.gz)
After some feature list discussion on the community forum about implementing a controlled gate module for any two-dimensional gate according to Barenco, I have finished the first test python files. I use the projectQ package and did a run with a controlled gate test.py, and it worked for the X gate.
Next step for me is to produce an output file in IBM QASM2 format.

**Comment by diego-plan9** [comment]
Hi @sensor1,

as part of a review of old issues, I'm wondering if you are still interested in contributing to the project and implementing the features you mention? It would be great if you could reopen the contribution in a form of a pull request instead of uploading the files, so we can assist and provide feedback more easily about the changes - please check the [Contributing guide](https://github.com/QISKit/qiskit-sdk-py/blob/master/CONTRIBUTING.rst).

Also, since it has been a while since the issue was opened and a number of changes have happened in the meantime, it might be helpful to note that:
- new gate definitions are usually placed in `qiskit/extensions` - #210 can be a good source of inspiration
- the test files are generally placed in `tests/python/test_foo.py`
- we now have a backend for ProjectQ simulator - #138
- also, please note that we currently do not have a dependency on `projectq` (only optional, for using with the simulator): it seems a good part of your code makes use of their gates and other machinery, which might be an issue - ideally, the implementation should only depend on the QISKit SDK internals if possible.

I'm closing the issue for keeping the repository more manageable, but please feel free to reopen for re-discussing before the PR, or for any other assistance we might be able to provide! Thanks!
